spring:
  application:
    name: graphql-demo
  graphql:
    schema:
      printer:
        enabled: true
    graphiql:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      format_sql: true
      use_sql_comments: true
      show-sql: true
      ddl-auto: update
    show-sql: true
